ktor:
    development: true
    application:
        modules:
            - com.modules.ApplicationKt.module
    deployment:
        port: 8080

postgres:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/postgres"
  user: "postgres"
  password: "password"
