package com.modules.db.other

object ConstsDB{
    const val STUDENT = "student"
    const val STUDENTS = "students"
    const val TEACHER = "teacher"
    const val TEACHERS = "teachers"
    const val HEADMASTER = "headmaster"
    const val ADMIN = "admin"
    const val N_A = "N/A"
    const val INDEX = "index"
    const val USERNAME = "username"
    const val USER_TYPE = "user_type"
    const val CLASS_NBR = "class_nbr"
    const val CLASSES = "classes"
    const val CLASS_TEACHER_NAME = "class_teacher_name"
    const val SUBJECTS = "subjects"
    const val SUBJECT_NAME = "subject_name"
    const val SUBJECT_INDEX = "subject_index"
    const val DESCRIPTION = "description"
    const val NO_DESCR_AVAILABLE = "No description available"
    const val PASSWORDS = "passwords"
    const val PASSWORD = "password"
    const val SUPER_ADMIN = "superAdmin"
    const val SALT = "salt"
}
